### ISSUE TITLE
DangerouslySetInnerHTML: Some bugs

### ISSUE THREAD

**Issue by steakscience** [sergeysolovev/react-hyphen#28]
Hi!
The soft hyphen is inserted before the first word and in classnames as well.
I think this is a bug

**Comment by sergeysolovev** [comment]
@steakscience yes it basically hyphenates the `dangerouslySetInnerHTML.__html` string (for simplicity’s sake). Otherwise, the markup has to be parsed, all content hyphenated separately.

I think for this purpose it’s better to use the [hyphenated](https://github.com/sergeysolovev/hyphenated) library directly (which `react-hyphen` is based on) in combination with some library which allow to break down the markup. What do you think?

**Comment by steakscience** [comment]
@sergeysolovev You're right, I will figure this out. Thanks!

**Comment by steakscience** [comment]
Turns out there is a library that does this just for Gatsby called `hypher`! No idea why `hypher` over `hyphen`
